# Generated by Django 4.0.5 on 2022-11-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='spec_device',
            field=models.TextField(null=True),
        ),
    ]
