# Generated by Django 4.0.5 on 2022-11-13 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='client_object',
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(default='Самара', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='manager',
            field=models.CharField(default='Manager', max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_manager',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
