# Generated by Django 4.0.5 on 2022-11-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_client_object_client_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_manager',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
