# Generated by Django 4.0.5 on 2022-10-10 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_foto_post_is_published_alter_post_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='foto',
        ),
    ]
