# Generated by Django 4.0.5 on 2022-11-15 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_client_phone_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='object',
        ),
        migrations.RemoveField(
            model_name='schema',
            name='name',
        ),
        migrations.RemoveField(
            model_name='schema',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='cat',
        ),
        migrations.DeleteModel(
            name='Cat',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Schema',
        ),
    ]
