# Generated by Django 4.0.5 on 2022-11-15 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_client_object_remove_schema_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
