# Generated by Django 4.0.5 on 2022-11-21 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_report_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.client'),
        ),
    ]
