# Generated by Django 4.0.5 on 2022-11-05 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('category_shcem', models.CharField(max_length=200)),
                ('first_layer', models.CharField(max_length=200)),
                ('dry_residue_first_layer', models.IntegerField(max_length=3)),
                ('second_layer', models.CharField(max_length=200)),
                ('thikness_first_layer', models.IntegerField(max_length=5)),
                ('dry_residue_second_layer', models.IntegerField(max_length=3)),
                ('thikness_second_layer', models.IntegerField(max_length=5)),
                ('all_thikness', models.IntegerField(max_length=5)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
        ),
    ]
