# Generated by Django 4.0.5 on 2022-11-05 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_schema_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='schema',
            field=models.CharField(max_length=200),
        ),
    ]
